# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

#  region: us-east-1

# The `service` block is the name of the service
service: weather-accuracy-lamdba

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  timeout: 240
  stage: dev # Default stage to be used. Default is "dev"

plugins:
  - serverless-offline
  #- serverless-local-schedule
functions:
  vilageFcstSetBatch:
    handler: shortWeather.vilageFcstBatch
    timeout: 600
    events:
      - schedule: 
          rate: cron(17 2,5,8,11,14,17,20,23 * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  ultraSrtNcstBatch:
    handler: shortWeather.ultraSrtNcstBatch
    events:
      - schedule: 
          rate: cron(45 * * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  ultraSrtFcstBatch:
    handler: shortWeather.ultraSrtFcstBatch
    events:
      - schedule: 
          rate: cron(47 * * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  midTaBatch:
    handler: shortWeather.midTaBatch
    events:
      - schedule: 
          rate: cron(10 9,21 * * ? *) # 9 -> 18, 21 -> 6
          #timezone: Asia/Seoul 
          enabled: true

  midLandFcstBatch:
    handler: shortWeather.midLandFcstBatch
    events:
      - schedule: 
          rate: cron(10 9,21 * * ? *) # 9 -> 18, 21 -> 6
          #timezone: Asia/Seoul 
          enabled: true

  gen1HourStats:
    handler: weatherStats.gen1HourStats
    timeout: 600
    events:
      - schedule: 
          rate: cron(55 * * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  gen3HourStats:
    handler: weatherStats.gen3HourStats
    timeout: 600
    events:
      - schedule: 
          rate: cron(1 1,4,7,10,11,16,19,22 * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  gen24HourStats:
    handler: weatherStats.gen24HourStats
    timeout: 600
    events:
      - schedule: 
          rate: cron(5 15 * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  setOutput:
    handler: weatherStats_output.output
    timeout: 120
    events:
      - schedule: 
          rate: cron(3 * * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  setOutput_3hours:
    handler: weatherStats_output_3hours.output
    timeout: 120
    events:
      - schedule: 
          rate: cron(5 1,4,7,10,11,16,19,22 * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true

  setOutput_24hours:
    handler: weatherStats_output_24hours.output
    timeout: 120
    events:
      - schedule: 
          rate: cron(7 15 * * ? *) 
          #timezone: Asia/Seoul 
          enabled: true